# Generated by Django 5.1.2 on 2025-03-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="wait_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
